#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ── GerontiCare × Backblaze B2 wizard ────────────────────────────────────────
# Configura o storage de anexos clínicos (S3-compatible) para produção no Vercel.
# Fluxo: conta B2 → bucket → app key → endpoint → .env.local → Vercel (Prod+Preview).
# O app NÃO muda — o driver s3 já lê S3_* (lib/storage/s3.ts).

TOTAL_STAGES=6
TOTAL_MINUTES=15

banner "Backblaze B2 — anexos clínicos (GerontiCare)"

# ── 1. Conta B2 ─────────────────────────────────────────────────────────────
stage "Conta Backblaze B2" 3
say "O Backblaze B2 tem 10 GB grátis permanentes + egress grátis (3x o armazenado)."
say "Se ainda não tiver conta, crie uma — o free tier não pede cartão."
open_url "https://www.backblaze.com/sign-up/cloud-storage"
step "Crie sua conta (e-mail + senha). Não precisa de cartão no free tier."
step "Confirme o e-mail e faça login no dashboard."
pause "Pressione Enter depois de logado no dashboard do B2."

# ── 2. Bucket ───────────────────────────────────────────────────────────────
stage "Criar bucket geronticare-anexos" 3
say "O bucket guarda os anexos clínicos. Precisa ser PRIVADO."
open_url "https://secure.backblaze.com/b2_buckets.htm"
step "Clique em 'Create a Bucket'."
step "Nome: geronticare-anexos"
step "Files in Bucket: Private (importante! anexos clínicos são confidenciais)"
step "Deixe o resto como está e clique em 'Create a Bucket'."
pause "Pressione Enter depois que o bucket for criado."

# ── 3. Application Key ──────────────────────────────────────────────────────
stage "Criar Application Key (S3)" 4
say "Uma App Key dá acesso programático ao bucket. Será o par Access Key ID + Secret."
open_url "https://secure.backblaze.com/b2_app_keys.htm"
step "Clique em 'Generate New Application Key'."
step "Name of Key: geronticare-s3 (ou qualquer nome)"
step "Allow access to Bucket(s): marque apenas o bucket geronticare-anexos"
step "Capabilities: deixe as padrão (inclui List/Read/Write/Delete)."
step "Clique em 'Generate New Application Key'."
say ""
say "A tela mostra 'applicationKeyId' e 'applicationKey' — copie os DOIS agora,"
say "pois o secret só aparece UMA vez."
ask_secret S3_ACCESS_KEY_ID   "Access Key ID (applicationKeyId):"
ask_secret S3_SECRET_ACCESS_KEY "Secret (applicationKey):"
write_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
write_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"

# ── 4. Endpoint S3 da região ────────────────────────────────────────────────
stage "Endpoint S3 da sua região" 2
say "O endpoint é https://s3.<regiao>.backblazeb2.com (ex.: s3.us-east-005.backblazeb2.com)."
say "Sua região aparece no dashboard — página de Account ou no canto da tela."
open_url "https://secure.backblaze.com/b2_buckets.htm"
step "Encontre o endpoint S3 da sua região (costuma estar em 'Account Details' ou ao lado do bucket)."
step "Formato: https://s3.<regiao>.backblazeb2.com (SEM o nome do bucket)."
ask S3_ENDPOINT "Paste o endpoint S3 (ex.: https://s3.us-east-005.backblazeb2.com):"
# Normaliza: garante https:// e remove barra final
S3_ENDPOINT="${S3_ENDPOINT%/}"
[[ "$S3_ENDPOINT" != https://* ]] && S3_ENDPOINT="https://$S3_ENDPOINT"
write_env S3_ENDPOINT "$S3_ENDPOINT"

# ── 5. Configurar driver + .env.local ───────────────────────────────────────
stage "Ativar storage S3 no app" 2
say "Agora ligamos o driver s3 e fixamos o nome do bucket."
ask S3_BUCKET "Nome do bucket (default geronticare-anexos):"
[[ -z "$S3_BUCKET" ]] && S3_BUCKET="geronticare-anexos"
write_env STORAGE_DRIVER "s3"
write_env S3_BUCKET "$S3_BUCKET"
note "S3_REGION fica como 'us-east-1' (o B2 ignora região no client, usa o endpoint)."

# ── 6. Sincronizar com Vercel (Production + Preview) ───────────────────────
stage "Publicar no Vercel (Production + Preview)" 3
say "Vamos criar as variáveis de ambiente no Vercel para os anexos funcionarem em produção."
if command -v vercel >/dev/null 2>&1 && vercel whoami >/dev/null 2>&1; then
  step "Adicionando STORAGE_DRIVER, S3_*, bucket e endpoint ao Vercel..."
  for env in production preview; do
    printf '%s' "s3" | vercel env add STORAGE_DRIVER "$env" >/dev/null 2>&1 && \
      printf '  %s✓%s STORAGE_DRIVER → %s\n' "$GREEN" "$RESET" "$env"
    printf '%s' "$S3_ENDPOINT" | vercel env add S3_ENDPOINT "$env" >/dev/null 2>&1 && \
      printf '  %s✓%s S3_ENDPOINT → %s\n' "$GREEN" "$RESET" "$env"
    printf '%s' "$S3_BUCKET" | vercel env add S3_BUCKET "$env" >/dev/null 2>&1 && \
      printf '  %s✓%s S3_BUCKET → %s\n' "$GREEN" "$RESET" "$env"
    printf '%s' "$S3_ACCESS_KEY_ID" | vercel env add S3_ACCESS_KEY_ID "$env" >/dev/null 2>&1 && \
      printf '  %s✓%s S3_ACCESS_KEY_ID → %s\n' "$GREEN" "$RESET" "$env"
    printf '%s' "$S3_SECRET_ACCESS_KEY" | vercel env add S3_SECRET_ACCESS_KEY "$env" >/dev/null 2>&1 && \
      printf '  %s✓%s S3_SECRET_ACCESS_KEY → %s\n' "$GREEN" "$RESET" "$env"
  done
  note "Se alguma já existia, o comando falha silenciosamente — rode manualmente:"
  note "  vercel env rm S3_<NOME> <env>  →  depois re-rode este wizard"
else
  warn "Vercel CLI não disponível/autenticado — configure as S3_* manualmente no dashboard do Vercel"
  SKIPPED+=("Vercel env vars (configure S3_* + STORAGE_DRIVER no dashboard do Vercel)")
fi

finish
